name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger AI Code Review Bot
        run: |
          curl -X POST "https://unswampy-unhewable-mauricio.ngrok-free.dev/review/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.event.pull_request.number }}" -H "accept: application/json"